import os
import django
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'orion_backend.settings')
django.setup()

from stocks.models import Stock

def load_stocks():
    created_count = 0
    skipped_count = 0
    stocks_data = [
        ('NVDA', 'Nvidia', 'US', 'General'),
        ('AAPL', 'Apple Inc.', 'US', 'General'),
        ('MSFT', 'Microsoft', 'US', 'General'),
        ('AMZN', 'Amazon', 'US', 'General'),
        ('GOOGL', 'Alphabet Inc. (Class A)', 'US', 'General'),
        ('GOOG', 'Alphabet Inc. (Class C)', 'US', 'General'),
        ('META', 'Meta Platforms', 'US', 'General'),
        ('AVGO', 'Broadcom', 'US', 'General'),
        ('TSLA', 'Tesla, Inc.', 'US', 'General'),
        ('BRK.B', 'Berkshire Hathaway', 'US', 'General'),
        ('WMT', 'Walmart', 'US', 'General'),
        ('LLY', 'Lilly (Eli)', 'US', 'General'),
        ('JPM', 'JPMorgan Chase', 'US', 'General'),
        ('XOM', 'ExxonMobil', 'US', 'General'),
        ('V', 'Visa Inc.', 'US', 'General'),
        ('JNJ', 'Johnson & Johnson', 'US', 'General'),
        ('MU', 'Micron Technology', 'US', 'General'),
        ('MA', 'Mastercard', 'US', 'General'),
        ('COST', 'Costco', 'US', 'General'),
        ('ORCL', 'Oracle Corporation', 'US', 'General'),
        ('CVX', 'Chevron Corporation', 'US', 'General'),
        ('NFLX', 'Netflix', 'US', 'General'),
        ('ABBV', 'AbbVie', 'US', 'General'),
        ('PLTR', 'Palantir Technologies', 'US', 'General'),
        ('BAC', 'Bank of America', 'US', 'General'),
        ('PG', 'Procter & Gamble', 'US', 'General'),
        ('AMD', 'Advanced Micro Devices', 'US', 'General'),
        ('KO', 'Coca-Cola Company (The)', 'US', 'General'),
        ('HD', 'Home Depot (The)', 'US', 'General'),
        ('CAT', 'Caterpillar Inc.', 'US', 'General'),
        ('CSCO', 'Cisco', 'US', 'General'),
        ('GE', 'GE Aerospace', 'US', 'General'),
        ('LRCX', 'Lam Research', 'US', 'General'),
        ('AMAT', 'Applied Materials', 'US', 'General'),
        ('MRK', 'Merck & Co.', 'US', 'General'),
        ('RTX', 'RTX Corporation', 'US', 'General'),
        ('MS', 'Morgan Stanley', 'US', 'General'),
        ('PM', 'Philip Morris International', 'US', 'General'),
        ('UNH', 'UnitedHealth Group', 'US', 'General'),
        ('GS', 'Goldman Sachs', 'US', 'General'),
        ('WFC', 'Wells Fargo', 'US', 'General'),
        ('TMUS', 'T-Mobile US', 'US', 'General'),
        ('GEV', 'GE Vernova', 'US', 'General'),
        ('IBM', 'IBM', 'US', 'General'),
        ('LIN', 'Linde plc', 'US', 'General'),
        ('MCD', 'McDonald\'s', 'US', 'General'),
        ('INTC', 'Intel', 'US', 'General'),
        ('VZ', 'Verizon', 'US', 'General'),
        ('PEP', 'PepsiCo', 'US', 'General'),
        ('AXP', 'American Express', 'US', 'General'),
        ('T', 'AT&T', 'US', 'General'),
        ('KLAC', 'KLA Corporation', 'US', 'General'),
        ('C', 'Citigroup', 'US', 'General'),
        ('AMGN', 'Amgen', 'US', 'General'),
        ('NEE', 'NextEra Energy', 'US', 'General'),
        ('ABT', 'Abbott Laboratories', 'US', 'General'),
        ('CRM', 'Salesforce', 'US', 'General'),
        ('DIS', 'Walt Disney Company (The)', 'US', 'General'),
        ('TMO', 'Thermo Fisher Scientific', 'US', 'General'),
        ('TJX', 'TJX Companies', 'US', 'General'),
        ('TXN', 'Texas Instruments', 'US', 'General'),
        ('GILD', 'Gilead Sciences', 'US', 'General'),
        ('ISRG', 'Intuitive Surgical', 'US', 'General'),
        ('SCHW', 'Charles Schwab Corporation', 'US', 'General'),
        ('ANET', 'Arista Networks', 'US', 'General'),
        ('APH', 'Amphenol', 'US', 'General'),
        ('COP', 'ConocoPhillips', 'US', 'General'),
        ('PFE', 'Pfizer', 'US', 'General'),
        ('BA', 'Boeing', 'US', 'General'),
        ('UBER', 'Uber', 'US', 'General'),
        ('DE', 'Deere & Company', 'US', 'General'),
        ('ADI', 'Analog Devices', 'US', 'General'),
        ('APP', 'AppLovin Corporation', 'US', 'General'),
        ('BLK', 'BlackRock', 'US', 'General'),
        ('LMT', 'Lockheed Martin', 'US', 'General'),
        ('HON', 'Honeywell', 'US', 'General'),
        ('UNP', 'Union Pacific Corporation', 'US', 'General'),
        ('QCOM', 'Qualcomm', 'US', 'General'),
        ('ETN', 'Eaton Corporation', 'US', 'General'),
        ('BKNG', 'Booking Holdings', 'US', 'General'),
        ('WELL', 'Welltower', 'US', 'General'),
        ('DHR', 'Danaher Corporation', 'US', 'General'),
        ('PANW', 'Palo Alto Networks', 'US', 'General'),
        ('SYK', 'Stryker Corporation', 'US', 'General'),
        ('SPGI', 'S&P Global', 'US', 'General'),
        ('LOW', 'Lowe\'s', 'US', 'General'),
        ('INTU', 'Intuit', 'US', 'General'),
        ('CB', 'Chubb Limited', 'US', 'General'),
        ('ACN', 'Accenture', 'US', 'General'),
        ('PGR', 'Progressive Corporation', 'US', 'General'),
        ('PLD', 'Prologis', 'US', 'General'),
        ('BMY', 'Bristol Myers Squibb', 'US', 'General'),
        ('NOW', 'ServiceNow', 'US', 'General'),
        ('VRTX', 'Vertex Pharmaceuticals', 'US', 'General'),
        ('PH', 'Parker Hannifin', 'US', 'General'),
        ('COF', 'Capital One', 'US', 'General'),
        ('MDT', 'Medtronic', 'US', 'General'),
        ('HCA', 'HCA Healthcare', 'US', 'General'),
        ('CME', 'CME Group', 'US', 'General'),
        ('MCK', 'McKesson Corporation', 'US', 'General'),
        ('MO', 'Altria', 'US', 'General'),
        ('GLW', 'Corning Inc.', 'US', 'General'),
        ('SBUX', 'Starbucks', 'US', 'General'),
        ('SNDK', 'Sandisk Corporation', 'US', 'General'),
        ('SO', 'Southern Company', 'US', 'General'),
        ('CMCSA', 'Comcast', 'US', 'General'),
        ('NEM', 'Newmont', 'US', 'General'),
        ('CRWD', 'CrowdStrike', 'US', 'General'),
        ('BSX', 'Boston Scientific', 'US', 'General'),
        ('CEG', 'Constellation Energy', 'US', 'General'),
        ('DELL', 'Dell Technologies', 'US', 'General'),
        ('ADBE', 'Adobe Inc.', 'US', 'General'),
        ('NOC', 'Northrop Grumman', 'US', 'General'),
        ('WDC', 'Western Digital', 'US', 'General'),
        ('DUK', 'Duke Energy', 'US', 'General'),
        ('EQIX', 'Equinix', 'US', 'General'),
        ('GD', 'General Dynamics', 'US', 'General'),
        ('WM', 'Waste Management', 'US', 'General'),
        ('HWM', 'Howmet Aerospace', 'US', 'General'),
        ('STX', 'Seagate Technology', 'US', 'General'),
        ('CVS', 'CVS Health', 'US', 'General'),
        ('TT', 'Trane Technologies', 'US', 'General'),
        ('ICE', 'Intercontinental Exchange', 'US', 'General'),
        ('WMB', 'Williams Companies', 'US', 'General'),
        ('BX', 'Blackstone Inc.', 'US', 'General'),
        ('MRSH', 'Marsh & McLennan Companies, Inc.', 'US', 'General'),
        ('MAR', 'Marriott International', 'US', 'General'),
        ('FDX', 'FedEx', 'US', 'General'),
        ('ADP', 'Automatic Data Processing', 'US', 'General'),
        ('PWR', 'Quanta Services', 'US', 'General'),
        ('AMT', 'American Tower', 'US', 'General'),
        ('UPS', 'United Parcel Service', 'US', 'General'),
        ('PNC', 'PNC Financial Services', 'US', 'General'),
        ('SNPS', 'Synopsys', 'US', 'General'),
        ('KKR', 'KKR', 'US', 'General'),
        ('USB', 'U.S. Bancorp', 'US', 'General'),
        ('JCI', 'Johnson Controls', 'US', 'General'),
        ('BK', 'BNY Mellon', 'US', 'General'),
        ('CDNS', 'Cadence Design Systems', 'US', 'General'),
        ('NKE', 'Nike, Inc.', 'US', 'General'),
        ('REGN', 'Regeneron Pharmaceuticals', 'US', 'General'),
        ('MCO', 'Moody\'s Corporation', 'US', 'General'),
        ('ABNB', 'Airbnb', 'US', 'General'),
        ('SHW', 'Sherwin-Williams', 'US', 'General'),
        ('MSI', 'Motorola Solutions', 'US', 'General'),
        ('FCX', 'Freeport-McMoRan', 'US', 'General'),
        ('EOG', 'EOG Resources', 'US', 'General'),
        ('MMM', '3M', 'US', 'General'),
        ('ITW', 'Illinois Tool Works', 'US', 'General'),
        ('CMI', 'Cummins', 'US', 'General'),
        ('ORLY', 'O\'Reilly Auto Parts', 'US', 'General'),
        ('KMI', 'Kinder Morgan', 'US', 'General'),
        ('ECL', 'Ecolab', 'US', 'General'),
        ('MNST', 'Monster Beverage', 'US', 'General'),
        ('MDLZ', 'Mondelez International', 'US', 'General'),
        ('EMR', 'Emerson Electric', 'US', 'General'),
        ('CTAS', 'Cintas', 'US', 'General'),
        ('VLO', 'Valero Energy', 'US', 'General'),
        ('RCL', 'Royal Caribbean Group', 'US', 'General'),
        ('CSX', 'CSX Corporation', 'US', 'General'),
        ('PSX', 'Phillips 66', 'US', 'General'),
        ('SLB', 'Schlumberger', 'US', 'General'),
        ('AON', 'Aon', 'US', 'General'),
        ('CI', 'Cigna', 'US', 'General'),
        ('MPC', 'Marathon Petroleum', 'US', 'General'),
        ('ROST', 'Ross Stores', 'US', 'General'),
        ('CL', 'Colgate-Palmolive', 'US', 'General'),
        ('DASH', 'DoorDash', 'US', 'General'),
        ('WBD', 'Warner Bros. Discovery', 'US', 'General'),
        ('AEP', 'American Electric Power', 'US', 'General'),
        ('RSG', 'Republic Services', 'US', 'General'),
        ('CRH', 'CRH plc', 'US', 'General'),
        ('HLT', 'Hilton Worldwide', 'US', 'General'),
        ('TDG', 'TransDigm Group', 'US', 'General'),
        ('LHX', 'L3Harris', 'US', 'General'),
        ('GM', 'General Motors', 'US', 'General'),
        ('APO', 'Apollo Global Management', 'US', 'General'),
        ('ELV', 'Elevance Health', 'US', 'General'),
        ('TRV', 'Travelers Companies (The)', 'US', 'General'),
        ('HOOD', 'Robinhood Markets, Inc.', 'US', 'General'),
        ('COR', 'Cencora', 'US', 'General'),
        ('NSC', 'Norfolk Southern Railway', 'US', 'General'),
        ('APD', 'Air Products', 'US', 'General'),
        ('FTNT', 'Fortinet', 'US', 'General'),
        ('SPG', 'Simon Property Group', 'US', 'General'),
        ('SRE', 'Sempra', 'US', 'General'),
        ('OXY', 'Occidental Petroleum', 'US', 'General'),
        ('BKR', 'Baker Hughes', 'US', 'General'),
        ('DLR', 'Digital Realty', 'US', 'General'),
        ('PCAR', 'Paccar', 'US', 'General'),
        ('TEL', 'TE Connectivity', 'US', 'General'),
        ('O', 'Realty Income', 'US', 'General'),
        ('OKE', 'ONEOK', 'US', 'General'),
        ('AJG', 'Arthur J. Gallagher & Co.', 'US', 'General'),
        ('AFL', 'Aflac', 'US', 'General'),
        ('TFC', 'Truist Financial', 'US', 'General'),
        ('CIEN', 'Ciena Corporation', 'US', 'General'),
        ('AZO', 'AutoZone', 'US', 'General'),
        ('FANG', 'Diamondback Energy', 'US', 'General'),
        ('ALL', 'Allstate', 'US', 'General'),
        ('360ONE.NS', '360 ONE WAM Ltd.', 'IN', 'Financial Services'),
        ('ABB.NS', 'ABB India Ltd.', 'IN', 'Capital Goods'),
        ('ACC.NS', 'ACC Ltd.', 'IN', 'Construction Materials'),
        ('APLAPOLLO.NS', 'APL Apollo Tubes Ltd.', 'IN', 'Capital Goods'),
        ('AUBANK.NS', 'AU Small Finance Bank Ltd.', 'IN', 'Financial Services'),
        ('ADANIENSOL.NS', 'Adani Energy Solutions Ltd.', 'IN', 'Power'),
        ('ADANIENT.NS', 'Adani Enterprises Ltd.', 'IN', 'Metals & Mining'),
        ('ADANIGREEN.NS', 'Adani Green Energy Ltd.', 'IN', 'Power'),
        ('ADANIPORTS.NS', 'Adani Ports and Special Economic Zone Ltd.', 'IN', 'Services'),
        ('ADANIPOWER.NS', 'Adani Power Ltd.', 'IN', 'Power'),
        ('ATGL.NS', 'Adani Total Gas Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('ABCAPITAL.NS', 'Aditya Birla Capital Ltd.', 'IN', 'Financial Services'),
        ('ALKEM.NS', 'Alkem Laboratories Ltd.', 'IN', 'Healthcare'),
        ('AMBUJACEM.NS', 'Ambuja Cements Ltd.', 'IN', 'Construction Materials'),
        ('APOLLOHOSP.NS', 'Apollo Hospitals Enterprise Ltd.', 'IN', 'Healthcare'),
        ('ASHOKLEY.NS', 'Ashok Leyland Ltd.', 'IN', 'Capital Goods'),
        ('ASIANPAINT.NS', 'Asian Paints Ltd.', 'IN', 'Consumer Durables'),
        ('ASTRAL.NS', 'Astral Ltd.', 'IN', 'Capital Goods'),
        ('AUROPHARMA.NS', 'Aurobindo Pharma Ltd.', 'IN', 'Healthcare'),
        ('DMART.NS', 'Avenue Supermarts Ltd.', 'IN', 'Consumer Services'),
        ('AXISBANK.NS', 'Axis Bank Ltd.', 'IN', 'Financial Services'),
        ('BSE.NS', 'BSE Ltd.', 'IN', 'Financial Services'),
        ('BAJAJ-AUTO.NS', 'Bajaj Auto Ltd.', 'IN', 'Automobile and Auto Components'),
        ('BAJFINANCE.NS', 'Bajaj Finance Ltd.', 'IN', 'Financial Services'),
        ('BAJAJFINSV.NS', 'Bajaj Finserv Ltd.', 'IN', 'Financial Services'),
        ('BAJAJHLDNG.NS', 'Bajaj Holdings & Investment Ltd.', 'IN', 'Financial Services'),
        ('BAJAJHFL.NS', 'Bajaj Housing Finance Ltd.', 'IN', 'Financial Services'),
        ('BANKBARODA.NS', 'Bank of Baroda', 'IN', 'Financial Services'),
        ('BANKINDIA.NS', 'Bank of India', 'IN', 'Financial Services'),
        ('BDL.NS', 'Bharat Dynamics Ltd.', 'IN', 'Capital Goods'),
        ('BEL.NS', 'Bharat Electronics Ltd.', 'IN', 'Capital Goods'),
        ('BHARATFORG.NS', 'Bharat Forge Ltd.', 'IN', 'Automobile and Auto Components'),
        ('BHEL.NS', 'Bharat Heavy Electricals Ltd.', 'IN', 'Capital Goods'),
        ('BPCL.NS', 'Bharat Petroleum Corporation Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('BHARTIARTL.NS', 'Bharti Airtel Ltd.', 'IN', 'Telecommunication'),
        ('BHARTIHEXA.NS', 'Bharti Hexacom Ltd.', 'IN', 'Telecommunication'),
        ('BIOCON.NS', 'Biocon Ltd.', 'IN', 'Healthcare'),
        ('BLUESTARCO.NS', 'Blue Star Ltd.', 'IN', 'Consumer Durables'),
        ('BOSCHLTD.NS', 'Bosch Ltd.', 'IN', 'Automobile and Auto Components'),
        ('BRITANNIA.NS', 'Britannia Industries Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('CGPOWER.NS', 'CG Power and Industrial Solutions Ltd.', 'IN', 'Capital Goods'),
        ('CANBK.NS', 'Canara Bank', 'IN', 'Financial Services'),
        ('CHOLAFIN.NS', 'Cholamandalam Investment and Finance Company Ltd.', 'IN', 'Financial Services'),
        ('CIPLA.NS', 'Cipla Ltd.', 'IN', 'Healthcare'),
        ('COALINDIA.NS', 'Coal India Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('COCHINSHIP.NS', 'Cochin Shipyard Ltd.', 'IN', 'Capital Goods'),
        ('COFORGE.NS', 'Coforge Ltd.', 'IN', 'Information Technology'),
        ('COLPAL.NS', 'Colgate Palmolive (India) Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('CONCOR.NS', 'Container Corporation of India Ltd.', 'IN', 'Services'),
        ('COROMANDEL.NS', 'Coromandel International Ltd.', 'IN', 'Chemicals'),
        ('CUMMINSIND.NS', 'Cummins India Ltd.', 'IN', 'Capital Goods'),
        ('DLF.NS', 'DLF Ltd.', 'IN', 'Realty'),
        ('DABUR.NS', 'Dabur India Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('DIVISLAB.NS', 'Divi\'s Laboratories Ltd.', 'IN', 'Healthcare'),
        ('DIXON.NS', 'Dixon Technologies (India) Ltd.', 'IN', 'Consumer Durables'),
        ('DRREDDY.NS', 'Dr. Reddy\'s Laboratories Ltd.', 'IN', 'Healthcare'),
        ('EICHERMOT.NS', 'Eicher Motors Ltd.', 'IN', 'Automobile and Auto Components'),
        ('ETERNAL.NS', 'Eternal Ltd.', 'IN', 'Consumer Services'),
        ('EXIDEIND.NS', 'Exide Industries Ltd.', 'IN', 'Automobile and Auto Components'),
        ('NYKAA.NS', 'FSN E-Commerce Ventures Ltd.', 'IN', 'Consumer Services'),
        ('FEDERALBNK.NS', 'Federal Bank Ltd.', 'IN', 'Financial Services'),
        ('FORTIS.NS', 'Fortis Healthcare Ltd.', 'IN', 'Healthcare'),
        ('GAIL.NS', 'GAIL (India) Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('GMRAIRPORT.NS', 'GMR Airports Ltd.', 'IN', 'Services'),
        ('GLENMARK.NS', 'Glenmark Pharmaceuticals Ltd.', 'IN', 'Healthcare'),
        ('GODFRYPHLP.NS', 'Godfrey Phillips India Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('GODREJCP.NS', 'Godrej Consumer Products Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('GODREJPROP.NS', 'Godrej Properties Ltd.', 'IN', 'Realty'),
        ('GRASIM.NS', 'Grasim Industries Ltd.', 'IN', 'Construction Materials'),
        ('HCLTECH.NS', 'HCL Technologies Ltd.', 'IN', 'Information Technology'),
        ('HDFCAMC.NS', 'HDFC Asset Management Company Ltd.', 'IN', 'Financial Services'),
        ('HDFCBANK.NS', 'HDFC Bank Ltd.', 'IN', 'Financial Services'),
        ('HDFCLIFE.NS', 'HDFC Life Insurance Company Ltd.', 'IN', 'Financial Services'),
        ('HAVELLS.NS', 'Havells India Ltd.', 'IN', 'Consumer Durables'),
        ('HEROMOTOCO.NS', 'Hero MotoCorp Ltd.', 'IN', 'Automobile and Auto Components'),
        ('HINDALCO.NS', 'Hindalco Industries Ltd.', 'IN', 'Metals & Mining'),
        ('HAL.NS', 'Hindustan Aeronautics Ltd.', 'IN', 'Capital Goods'),
        ('HINDPETRO.NS', 'Hindustan Petroleum Corporation Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('HINDUNILVR.NS', 'Hindustan Unilever Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('HINDZINC.NS', 'Hindustan Zinc Ltd.', 'IN', 'Metals & Mining'),
        ('POWERINDIA.NS', 'Hitachi Energy India Ltd.', 'IN', 'Capital Goods'),
        ('HUDCO.NS', 'Housing & Urban Development Corporation Ltd.', 'IN', 'Financial Services'),
        ('HYUNDAI.NS', 'Hyundai Motor India Ltd.', 'IN', 'Automobile and Auto Components'),
        ('ICICIBANK.NS', 'ICICI Bank Ltd.', 'IN', 'Financial Services'),
        ('ICICIGI.NS', 'ICICI Lombard General Insurance Company Ltd.', 'IN', 'Financial Services'),
        ('IDFCFIRSTB.NS', 'IDFC First Bank Ltd.', 'IN', 'Financial Services'),
        ('IRB.NS', 'IRB Infrastructure Developers Ltd.', 'IN', 'Construction'),
        ('ITCHOTELS.NS', 'ITC Hotels Ltd.', 'IN', 'Consumer Services'),
        ('ITC.NS', 'ITC Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('INDIANB.NS', 'Indian Bank', 'IN', 'Financial Services'),
        ('INDHOTEL.NS', 'Indian Hotels Co. Ltd.', 'IN', 'Consumer Services'),
        ('IOC.NS', 'Indian Oil Corporation Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('IRCTC.NS', 'Indian Railway Catering And Tourism Corporation Ltd.', 'IN', 'Consumer Services'),
        ('IRFC.NS', 'Indian Railway Finance Corporation Ltd.', 'IN', 'Financial Services'),
        ('IREDA.NS', 'Indian Renewable Energy Development Agency Ltd.', 'IN', 'Financial Services'),
        ('IGL.NS', 'Indraprastha Gas Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('INDUSTOWER.NS', 'Indus Towers Ltd.', 'IN', 'Telecommunication'),
        ('INDUSINDBK.NS', 'IndusInd Bank Ltd.', 'IN', 'Financial Services'),
        ('NAUKRI.NS', 'Info Edge (India) Ltd.', 'IN', 'Consumer Services'),
        ('INFY.NS', 'Infosys Ltd.', 'IN', 'Information Technology'),
        ('INDIGO.NS', 'InterGlobe Aviation Ltd.', 'IN', 'Services'),
        ('JSWENERGY.NS', 'JSW Energy Ltd.', 'IN', 'Power'),
        ('JSWSTEEL.NS', 'JSW Steel Ltd.', 'IN', 'Metals & Mining'),
        ('JINDALSTEL.NS', 'Jindal Steel Ltd.', 'IN', 'Metals & Mining'),
        ('JIOFIN.NS', 'Jio Financial Services Ltd.', 'IN', 'Financial Services'),
        ('JUBLFOOD.NS', 'Jubilant Foodworks Ltd.', 'IN', 'Consumer Services'),
        ('KEI.NS', 'KEI Industries Ltd.', 'IN', 'Capital Goods'),
        ('KPITTECH.NS', 'KPIT Technologies Ltd.', 'IN', 'Information Technology'),
        ('KALYANKJIL.NS', 'Kalyan Jewellers India Ltd.', 'IN', 'Consumer Durables'),
        ('KOTAKBANK.NS', 'Kotak Mahindra Bank Ltd.', 'IN', 'Financial Services'),
        ('LTF.NS', 'L&T Finance Ltd.', 'IN', 'Financial Services'),
        ('LICHSGFIN.NS', 'LIC Housing Finance Ltd.', 'IN', 'Financial Services'),
        ('LTM.NS', 'LTIMindtree Ltd.', 'IN', 'Information Technology'),
        ('LT.NS', 'Larsen & Toubro Ltd.', 'IN', 'Construction'),
        ('LICI.NS', 'Life Insurance Corporation of India', 'IN', 'Financial Services'),
        ('LODHA.NS', 'Lodha Developers Ltd.', 'IN', 'Realty'),
        ('LUPIN.NS', 'Lupin Ltd.', 'IN', 'Healthcare'),
        ('MRF.NS', 'MRF Ltd.', 'IN', 'Automobile and Auto Components'),
        ('M&MFIN.NS', 'Mahindra & Mahindra Financial Services Ltd.', 'IN', 'Financial Services'),
        ('M&M.NS', 'Mahindra & Mahindra Ltd.', 'IN', 'Automobile and Auto Components'),
        ('MANKIND.NS', 'Mankind Pharma Ltd.', 'IN', 'Healthcare'),
        ('MARICO.NS', 'Marico Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('MARUTI.NS', 'Maruti Suzuki India Ltd.', 'IN', 'Automobile and Auto Components'),
        ('MFSL.NS', 'Max Financial Services Ltd.', 'IN', 'Financial Services'),
        ('MAXHEALTH.NS', 'Max Healthcare Institute Ltd.', 'IN', 'Healthcare'),
        ('MAZDOCK.NS', 'Mazagoan Dock Shipbuilders Ltd.', 'IN', 'Capital Goods'),
        ('MOTILALOFS.NS', 'Motilal Oswal Financial Services Ltd.', 'IN', 'Financial Services'),
        ('MPHASIS.NS', 'MphasiS Ltd.', 'IN', 'Information Technology'),
        ('MUTHOOTFIN.NS', 'Muthoot Finance Ltd.', 'IN', 'Financial Services'),
        ('NHPC.NS', 'NHPC Ltd.', 'IN', 'Power'),
        ('NMDC.NS', 'NMDC Ltd.', 'IN', 'Metals & Mining'),
        ('NTPCGREEN.NS', 'NTPC Green Energy Ltd.', 'IN', 'Power'),
        ('NTPC.NS', 'NTPC Ltd.', 'IN', 'Power'),
        ('NATIONALUM.NS', 'National Aluminium Co. Ltd.', 'IN', 'Metals & Mining'),
        ('NESTLEIND.NS', 'Nestle India Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('OBEROIRLTY.NS', 'Oberoi Realty Ltd.', 'IN', 'Realty'),
        ('ONGC.NS', 'Oil & Natural Gas Corporation Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('OIL.NS', 'Oil India Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('PAYTM.NS', 'One 97 Communications Ltd.', 'IN', 'Financial Services'),
        ('OFSS.NS', 'Oracle Financial Services Software Ltd.', 'IN', 'Information Technology'),
        ('POLICYBZR.NS', 'PB Fintech Ltd.', 'IN', 'Financial Services'),
        ('PIIND.NS', 'PI Industries Ltd.', 'IN', 'Chemicals'),
        ('PAGEIND.NS', 'Page Industries Ltd.', 'IN', 'Textiles'),
        ('PATANJALI.NS', 'Patanjali Foods Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('PERSISTENT.NS', 'Persistent Systems Ltd.', 'IN', 'Information Technology'),
        ('PHOENIXLTD.NS', 'Phoenix Mills Ltd.', 'IN', 'Realty'),
        ('PIDILITIND.NS', 'Pidilite Industries Ltd.', 'IN', 'Chemicals'),
        ('POLYCAB.NS', 'Polycab India Ltd.', 'IN', 'Capital Goods'),
        ('PFC.NS', 'Power Finance Corporation Ltd.', 'IN', 'Financial Services'),
        ('POWERGRID.NS', 'Power Grid Corporation of India Ltd.', 'IN', 'Power'),
        ('PREMIERENE.NS', 'Premier Energies Ltd.', 'IN', 'Capital Goods'),
        ('PRESTIGE.NS', 'Prestige Estates Projects Ltd.', 'IN', 'Realty'),
        ('PNB.NS', 'Punjab National Bank', 'IN', 'Financial Services'),
        ('RECLTD.NS', 'REC Ltd.', 'IN', 'Financial Services'),
        ('RVNL.NS', 'Rail Vikas Nigam Ltd.', 'IN', 'Construction'),
        ('RELIANCE.NS', 'Reliance Industries Ltd.', 'IN', 'Oil Gas & Consumable Fuels'),
        ('SBICARD.NS', 'SBI Cards and Payment Services Ltd.', 'IN', 'Financial Services'),
        ('SBILIFE.NS', 'SBI Life Insurance Company Ltd.', 'IN', 'Financial Services'),
        ('SRF.NS', 'SRF Ltd.', 'IN', 'Chemicals'),
        ('MOTHERSON.NS', 'Samvardhana Motherson International Ltd.', 'IN', 'Automobile and Auto Components'),
        ('SHREECEM.NS', 'Shree Cement Ltd.', 'IN', 'Construction Materials'),
        ('SHRIRAMFIN.NS', 'Shriram Finance Ltd.', 'IN', 'Financial Services'),
        ('ENRIN.NS', 'Siemens Energy India Ltd.', 'IN', 'Capital Goods'),
        ('SIEMENS.NS', 'Siemens Ltd.', 'IN', 'Capital Goods'),
        ('SOLARINDS.NS', 'Solar Industries India Ltd.', 'IN', 'Chemicals'),
        ('SONACOMS.NS', 'Sona BLW Precision Forgings Ltd.', 'IN', 'Automobile and Auto Components'),
        ('SBIN.NS', 'State Bank of India', 'IN', 'Financial Services'),
        ('SAIL.NS', 'Steel Authority of India Ltd.', 'IN', 'Metals & Mining'),
        ('SUNPHARMA.NS', 'Sun Pharmaceutical Industries Ltd.', 'IN', 'Healthcare'),
        ('SUPREMEIND.NS', 'Supreme Industries Ltd.', 'IN', 'Capital Goods'),
        ('SUZLON.NS', 'Suzlon Energy Ltd.', 'IN', 'Capital Goods'),
        ('SWIGGY.NS', 'Swiggy Ltd.', 'IN', 'Consumer Services'),
        ('TVSMOTOR.NS', 'TVS Motor Company Ltd.', 'IN', 'Automobile and Auto Components'),
        ('TATACOMM.NS', 'Tata Communications Ltd.', 'IN', 'Telecommunication'),
        ('TCS.NS', 'Tata Consultancy Services Ltd.', 'IN', 'Information Technology'),
        ('TATACONSUM.NS', 'Tata Consumer Products Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('TATAELXSI.NS', 'Tata Elxsi Ltd.', 'IN', 'Information Technology'),
        ('TMPV.NS', 'Tata Motors Passenger Vehicles Ltd.', 'IN', 'Automobile and Auto Components'),
        ('TATAPOWER.NS', 'Tata Power Co. Ltd.', 'IN', 'Power'),
        ('TATASTEEL.NS', 'Tata Steel Ltd.', 'IN', 'Metals & Mining'),
        ('TATATECH.NS', 'Tata Technologies Ltd.', 'IN', 'Information Technology'),
        ('TECHM.NS', 'Tech Mahindra Ltd.', 'IN', 'Information Technology'),
        ('TITAN.NS', 'Titan Company Ltd.', 'IN', 'Consumer Durables'),
        ('TORNTPHARM.NS', 'Torrent Pharmaceuticals Ltd.', 'IN', 'Healthcare'),
        ('TORNTPOWER.NS', 'Torrent Power Ltd.', 'IN', 'Power'),
        ('TRENT.NS', 'Trent Ltd.', 'IN', 'Consumer Services'),
        ('TIINDIA.NS', 'Tube Investments of India Ltd.', 'IN', 'Automobile and Auto Components'),
        ('UPL.NS', 'UPL Ltd.', 'IN', 'Chemicals'),
        ('ULTRACEMCO.NS', 'UltraTech Cement Ltd.', 'IN', 'Construction Materials'),
        ('UNIONBANK.NS', 'Union Bank of India', 'IN', 'Financial Services'),
        ('UNITDSPR.NS', 'United Spirits Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('VBL.NS', 'Varun Beverages Ltd.', 'IN', 'Fast Moving Consumer Goods'),
        ('VEDL.NS', 'Vedanta Ltd.', 'IN', 'Metals & Mining'),
        ('VMM.NS', 'Vishal Mega Mart Ltd.', 'IN', 'Consumer Services'),
        ('IDEA.NS', 'Vodafone Idea Ltd.', 'IN', 'Telecommunication'),
        ('VOLTAS.NS', 'Voltas Ltd.', 'IN', 'Consumer Durables'),
        ('WAAREEENER.NS', 'Waaree Energies Ltd.', 'IN', 'Capital Goods'),
        ('WIPRO.NS', 'Wipro Ltd.', 'IN', 'Information Technology'),
        ('YESBANK.NS', 'Yes Bank Ltd.', 'IN', 'Financial Services'),
        ('ZYDUSLIFE.NS', 'Zydus Lifesciences Ltd.', 'IN', 'Healthcare'),
    ]

    for symbol, name, market, sector in stocks_data:
        obj, created = Stock.objects.get_or_create(
            symbol=symbol,
            defaults={'name': name, 'market': market, 'sector': sector}
        )
        if created:
            created_count += 1
        else:
            skipped_count += 1

    print(f'Done! Created: {created_count}, Already existed: {skipped_count}')

if __name__ == '__main__':
    load_stocks()