# Generated by Django 6.0.3 on 2026-03-23 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Score from -1 (negative) to +1 (positive)"
                    ),
                ),
                ("raw_text", models.TextField(blank=True, null=True)),
                (
                    "model_used",
                    models.CharField(default="ProsusAI/finbert", max_length=100),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiments",
                        to="news.newsarticle",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiments",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment Result",
                "verbose_name_plural": "Sentiment Results",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="StockSentimentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("avg_score", models.FloatField()),
                ("positive_count", models.IntegerField(default=0)),
                ("negative_count", models.IntegerField(default=0)),
                ("neutral_count", models.IntegerField(default=0)),
                ("total_articles", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_summaries",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment Summary",
                "verbose_name_plural": "Sentiment Summaries",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
