# Generated by Django 6.0.3 on 2026-03-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=20)),
                ('quality_score', models.FloatField(default=0.0)),
                ('rank_in_sector', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sector', 'rank_in_sector'],
            },
        ),
        migrations.CreateModel(
            name='StockAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('full_report', models.TextField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('recommendation', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('model_used', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='quality_stocks.qualitystock')),
            ],
        ),
        migrations.CreateModel(
            name='StockFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('pb_ratio', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('revenue_growth_yoy', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('week_52_high', models.FloatField(blank=True, null=True)),
                ('week_52_low', models.FloatField(blank=True, null=True)),
                ('avg_volume', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('price_history_json', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='quality_stocks.qualitystock')),
            ],
        ),
    ]
