# Generated by Django 6.0.3 on 2026-03-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=1000, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("newsapi", "NewsAPI"),
                            ("finnhub", "Finnhub"),
                            ("scraped", "Scraped"),
                        ],
                        default="newsapi",
                        max_length=20,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("published_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_stocks",
                    models.ManyToManyField(
                        blank=True, related_name="news", to="stocks.stock"
                    ),
                ),
            ],
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
                "ordering": ["-published_at"],
            },
        ),
    ]
